const c = {
  CHANGE_ROWS_COUNT: 'CHANGE_ROWS_COUNT',
  CHANGE_COLUMNS_COUNT: 'CHANGE_COLUMNS_COUNT',
  UPDATE_MATRIX: 'UPDATE_MATRIX',
  CHANGE_NEEDS: 'CHANGE_NEEDS',
  CHANGE_STORAGE: 'CHANGE_STORAGE',

  GET_STORAGE_VOLUME: 'GET_STORAGE_VOLUME',
  GET_NEEDS_VOLUME: 'GET_NEEDS_VOLUME',
  UPDATE_STATE: 'UPDATE_STATE'
}

export default c;